development:
  adapter: sqlite3
  encoding: utf8
  database: db/task_dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: db/task_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  encoding: utf8
  database: db/task_prod.sqlite3
  pool: 5
  timeout: 5000